name: app_turista
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.14
  flutter_verification_code: ^1.1.2+1
  carousel_slider: ^5.0.0
  badges: ^3.1.2
  camera: ^0.11.0+2
  path_provider: ^2.0.9
  photo_manager: ^3.6.1
  provider: ^6.0.2
  extended_image: ^9.0.7
  image: ^4.3.0
  image_cropper: ^8.0.2
  video_player: ^2.3.0
  photo_manager_image_provider: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/users/
    - assets/images/moments/
    - assets/images/reels/
    - assets/icons/

  fonts:
    - family: 'Proxima Nova'
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.ttf
        - asset: assets/fonts/ProximaNova-Medium.ttf
          weight: 500
        - asset: assets/fonts/ProximaNova-Semibold.ttf
          weight: 600
        - asset: assets/fonts/ProximaNova-Bold.ttf
          weight: 700
    - family: 'Proxima Soft'
      fonts:
        - asset: assets/fonts/ProximaSoft-Regular.ttf
        - asset: assets/fonts/ProximaSoft-Bold.ttf
          weight: 700
